development:
  adapter: postgresql
  encoding: unicode
  database: epicsale_development
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: epicsale_test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: epicsale_production
  password:
