development:
  adapter: postgresql
  encoding: unicode
  database: sose_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sose_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sose_production
  pool: 5
  password:

